spring:
  datasource:
    url: ${MYSQL_URL}
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      #      show_sql: true
      format_sql: true

  cloud:
    gcp:
      credentials:
        location: classpath:key.json
logging:
  pattern:
    path:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
  level:
    sql: debug
    org.hibernate.type: trace

gcp:
  project:
    id: ${PROJECT_ID}
    bucket:
      name: ${BUCKET_NAME}
      key-path: ${KEY_PATH}

jwt:
  token:
    secret-key: ${JWT_SECRET_KEY}
    access:
      expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
    refresh:
      expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}
