spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  datasource:
    url: ${MYSQL_URL}
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      #      show_sql: true
      format_sql: true

  cloud:
    gcp:
      credentials:
        location: classpath:key.json
logging:
  pattern:
    path:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
  level:
    sql: debug
    org.hibernate.type: trace

gcp:
  project:
    id: ${PROJECT_ID}
    bucket:
      name: ${BUCKET_NAME}
      key-path: ${KEY_PATH}
      ttl: ${DURATION}
      
ai-url: ${INFERENCE_URL}

deepl-auth-key: ${DEEPL_AUTH_KEY}

papago-auth:
  id : ${PAPAGO_AUTH_ID}
  key : ${PAPAGO_AUTH_KEY}


jwt:
  token:
    secret-key: ${JWT_SECRET_KEY}
    access:
      expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
    refresh:
      expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}

springdoc:
  version: '1.16.5'
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  show-actuator: true

swagger:
  request-url: http://localhost:8080
  description: 로컬 서버

cors:
  list : ${CORS_LIST}
