spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_schema?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: kor159753!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      #      show_sql: true
      format_sql: true

  cloud:
    gcp:
      credentials:
        location: classpath:key.json
logging:
  level:
    sql: debug
    org.hibernate.type: trace
