spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    converters:
      preferred-json-mapper: gson
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none

  cloud:
    gcp:
      credentials:
        location: file:${KEY_PATH}
logging:
  pattern:
    path:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] %logger[%method:%line] - %msg%n"
  level:
    org.springframework: WARN
    org.hibernate.SQL: WARN
    mmm.emopic: WARN
  file:
    path: ${LOG_PATH}
    logback:
      rollingpolicy:
        file-name-pattern:
          ${LOG_PATH}/%d{yyyy-MM-dd}/Log-%d{yyyy-MM-dd}.%i.log
gcp:
  project:
    id: ${PROJECT_ID}
    bucket:
      name: ${BUCKET_NAME}
      key-path: ${KEY_PATH}

ai-url: ${INFERENCE_URL}

deepl-auth-key: ${DEEPL_AUTH_KEY}

jwt:
  token:
    secret-key: ${JWT_SECRET_KEY}
    access:
      expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
    refresh:
      expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}

springdoc:
  version: '1.6.15'
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  show-actuator: true

swagger:
  request-url: ${REQUEST_URL}
  description: ${REQUEST_URL_DESCRIPTION}

cors:
  list : ${CORS_LIST}


kakao:
  api:
    key: ${KAKAO_REST_API_KEY}
    geo:
      coord2regioncode: ${KAKAO_COORD_TO_REGION_URL}